"""HALO Agent 01 asset rendering - the one genuinely-executing capability.

Maps Agent 01's real final_draft schema (copy.* + visual_spec.*) into a real,
downloadable branded HTML asset file. DEMO execution: HTML renders as a real
visual asset with no external deps. Production would render PNG/PDF - roadmap.
"""
import html
import logging

logger = logging.getLogger("halo.asset")


def render_brand_asset(brand_output):
    """Render Agent 01 final_draft into a standalone branded HTML asset file."""
    draft = brand_output or {}
    copy = draft.get("copy") or {}
    visual = draft.get("visual_spec") or {}

    headline = copy.get("headline") or "On-brand asset"
    subhead = copy.get("subhead") or ""
    body = copy.get("body") or ""
    cta = copy.get("cta") or ""

    concept = visual.get("concept") or ""
    mood = visual.get("mood") or []
    palette = visual.get("palette") or []
    composition = visual.get("composition") or ""

    if isinstance(mood, list):
        mood_str = ", ".join(str(m) for m in mood)
    else:
        mood_str = str(mood)

    swatches = [str(p) for p in palette if isinstance(p, str)] if isinstance(palette, list) else []

    h = html.escape(str(headline))
    sh = html.escape(str(subhead))
    b = html.escape(str(body))
    c = html.escape(str(cta))
    concept_e = html.escape(str(concept))
    mood_e = html.escape(mood_str)
    comp_e = html.escape(str(composition))

    primary = swatches[0] if swatches else "#002B5C"
    accent = swatches[1] if len(swatches) > 1 else "#00A3E0"
    light = swatches[2] if len(swatches) > 2 else "#E5F4FF"

    swatch_html = "".join(
        '<div style="display:flex;align-items:center;gap:8px;margin:6px 0">'
        '<span style="width:26px;height:26px;border-radius:6px;display:inline-block;'
        'border:1px solid rgba(0,0,0,0.1);background:{hx}"></span>'
        '<code style="font-size:12px;color:#475569">{hx}</code></div>'.format(hx=html.escape(str(s)))
        for s in swatches
    )

    asset = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HALO Asset - {headline}</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; background:#f1f5f9; padding:40px; color:#0f172a; }}
  .asset {{ max-width:760px; margin:0 auto; background:#fff; border-radius:16px; overflow:hidden; box-shadow:0 10px 40px rgba(0,0,0,0.10); }}
  .hero {{ background:linear-gradient(135deg,{primary} 0%,{accent} 100%); color:#fff; padding:60px 52px; }}
  .hero .kicker {{ font-size:12px; letter-spacing:0.18em; text-transform:uppercase; opacity:0.85; margin-bottom:18px; }}
  .hero h1 {{ font-size:36px; line-height:1.18; font-weight:700; margin-bottom:14px; }}
  .hero .subhead {{ font-size:18px; line-height:1.5; opacity:0.92; font-weight:400; }}
  .content {{ padding:44px 52px; }}
  .content .body {{ font-size:17px; line-height:1.7; color:#334155; }}
  .cta {{ display:inline-block; margin-top:30px; background:{primary}; color:#fff; padding:15px 30px; border-radius:8px; font-weight:600; font-size:15px; text-decoration:none; }}
  .spec {{ border-top:1px solid #e2e8f0; padding:32px 52px; background:{light}; }}
  .spec h3 {{ font-size:11px; letter-spacing:0.14em; text-transform:uppercase; color:#64748b; margin:0 0 10px; }}
  .spec .row {{ margin-bottom:20px; }}
  .spec .val {{ font-size:14px; line-height:1.6; color:#334155; }}
  .footer {{ padding:20px 52px; font-size:11px; color:#94a3b8; text-align:center; background:#f8fafc; border-top:1px solid #eef2f6; }}
</style></head>
<body>
  <div class="asset">
    <div class="hero">
      <div class="kicker">HALO &middot; Brand &amp; Brief</div>
      <h1>{headline}</h1>
      {subhead_block}
    </div>
    <div class="content">
      <div class="body">{body}</div>
      {cta_block}
    </div>
    <div class="spec">
      {concept_block}
      {mood_block}
      {comp_block}
      {palette_block}
    </div>
    <div class="footer">Generated by HALO &middot; on-brand, policy-checked, validator-approved &middot; demo asset</div>
  </div>
</body></html>""".format(
        headline=h,
        subhead_block='<div class="subhead">{}</div>'.format(sh) if sh else "",
        body=b or "(no body copy generated)",
        cta_block='<a class="cta" href="#">{}</a>'.format(c) if c else "",
        concept_block=('<div class="row"><h3>Visual concept</h3><div class="val">{}</div></div>'.format(concept_e)) if concept_e else "",
        mood_block=('<div class="row"><h3>Mood</h3><div class="val">{}</div></div>'.format(mood_e)) if mood_e else "",
        comp_block=('<div class="row"><h3>Composition</h3><div class="val">{}</div></div>'.format(comp_e)) if comp_e else "",
        palette_block=('<div class="row"><h3>Palette</h3>' + swatch_html + '</div>') if swatch_html else "",
        primary=html.escape(str(primary)),
        accent=html.escape(str(accent)),
        light=html.escape(str(light)),
    )
    logger.info("ASSET_RENDERED | headline={!r} | swatches={}".format(str(headline)[:40], len(swatches)))
    return asset
